baseURL: "https://adelatorre2.github.io/"
title: Alejandro De La Torre
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: about
          url: books/
          weight: 5 
        - name: work
          url: papers/
          weight: 2
        - name: projects
          url: courses/
          weight: 3
        - name: resume
          url: data/
          weight: 4 
        - name: contact me!
          url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
          weight: 6

params:
    description: "This website hosts Moritz-Maria von Igelfeld's research papers, books, course materials, data, curriculum vitae, and contact information."
    author: Moritz-Maria von Igelfeld
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Professor Dr von Igelfeld
          subtitle: "üëã hi, i‚Äôm @adelatorre2\n\nüìä economics (math emphasis) + information science (analytics)\n‚öñÔ∏è interested in applied econ, data analytics, and antitrust/IO\nüß† research + visualization + building clean, useful tools\n‚ö° explore my work and let‚Äôs get in touch!"
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: about
              url: books/
            - name: work
              url: papers/
            - name: projects
              url: courses/
            - name: resume
              url: data/
            - name: contact me!
              url: location/

    socialIcons:
        - name: LinkedIn
          url: https://www.linkedin.com/in/adelatorre2/
        - name: GitHub
          url: https://github.com/adelatorre2
        - name: Twitter
          url: https://x.com/AlejDLT
        - name: Bluesky
          url: https://bsky.app/profile/alejdlt.bsky.social
        - name: Email
          url: mailto:alexdelatorre@wisc.edu
        - name: Resume
          url: adlt_resume.pdf

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Moritz-Maria von Igelfeld"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2